# Generated by Django 3.2.9 on 2021-11-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reservation_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='leave_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_at',
            field=models.DateTimeField(),
        ),
    ]
