# Generated by Django 3.2.9 on 2021-11-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_reservation_room_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='leave_at',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='start_at',
            new_name='check_out',
        ),
    ]
